# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "思遥方 & 思源千年的博客"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Seayay's Blog"
weight = 2